# Generated by Django 3.1.3 on 2023-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.TextField(default='2003')),
                ('descripcion', models.TextField(default='')),
                ('serie', models.TextField(default='')),
                ('color', models.TextField(default='')),
                ('transmision', models.TextField(default='Manual')),
                ('version', models.TextField(default='standard')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('numero_cilindros', models.PositiveSmallIntegerField(default=4)),
                ('numero_puertas', models.PositiveSmallIntegerField(default=4)),
                ('combustible', models.TextField(default='Gasolina')),
            ],
        ),
    ]
