# Generated by Django 3.1.3 on 2023-03-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20230224_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='numero_cilindros',
            new_name='numerocilindros',
        ),
        migrations.RenameField(
            model_name='auto',
            old_name='numero_puertas',
            new_name='numeropuertas',
        ),
    ]
